# ---
# - hosts: all
#   vars:
#     my_env_var: "{{ lookup('ansible.builtin.env', 'hameed') }}"
#   tasks:
#     - name: Print the environment variable value
#       debug:
#         msg: "The value of MY_VAR is: {{ my_env_var }}"
---
- name: Display Variables
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Display my_var1
      debug:
        msg: "my_var1 is {{ ansible_user }}"

    - name: Display my_var2
      debug:
        msg: "my_var2 is {{ ansible_password }}"

